version: "3.9"
services:
  mango-service-v4:
    build: mango-service-v4
    ports:
      - "3000:3000"
    volumes:
      - ~/.config/solana:/root/.config/solana # mount volume where keys are present, also see PRIVATE_KEY_PATH
    environment:
      - PORT=3000
      - GROUP_NAME=mainnet.1
      - CLUSTER_URL=${CLUSTER_URL} # configure custom RPC node
      - PRIVATE_KEY_PATH=/root/.config/solana/id.json # configure path to private keypair here
  reverse-proxy:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf # custom config which unifies mango-service-v4